//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DungeonMap.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDungeonMapListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class DungeonMapBaseListener : IDungeonMapListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] DungeonMapParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] DungeonMapParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElem([NotNull] DungeonMapParser.ElemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElem([NotNull] DungeonMapParser.ElemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createFirstCorrSect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateFirstCorrSect([NotNull] DungeonMapParser.CreateFirstCorrSectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createFirstCorrSect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateFirstCorrSect([NotNull] DungeonMapParser.CreateFirstCorrSectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createSecondCorrSect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateSecondCorrSect([NotNull] DungeonMapParser.CreateSecondCorrSectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createSecondCorrSect"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateSecondCorrSect([NotNull] DungeonMapParser.CreateSecondCorrSectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createRoom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateRoom([NotNull] DungeonMapParser.CreateRoomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createRoom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateRoom([NotNull] DungeonMapParser.CreateRoomContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
