//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GameSetup.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GameSetupParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IGameSetupListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] GameSetupParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] GameSetupParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElem([NotNull] GameSetupParser.ElemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElem([NotNull] GameSetupParser.ElemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.initialiseGame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialiseGame([NotNull] GameSetupParser.InitialiseGameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.initialiseGame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialiseGame([NotNull] GameSetupParser.InitialiseGameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.defineGame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefineGame([NotNull] GameSetupParser.DefineGameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.defineGame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefineGame([NotNull] GameSetupParser.DefineGameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.createPlayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreatePlayer([NotNull] GameSetupParser.CreatePlayerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.createPlayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreatePlayer([NotNull] GameSetupParser.CreatePlayerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.createDungeon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateDungeon([NotNull] GameSetupParser.CreateDungeonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.createDungeon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateDungeon([NotNull] GameSetupParser.CreateDungeonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.createEnemies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateEnemies([NotNull] GameSetupParser.CreateEnemiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.createEnemies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateEnemies([NotNull] GameSetupParser.CreateEnemiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.finishGameSetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinishGameSetup([NotNull] GameSetupParser.FinishGameSetupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.finishGameSetup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinishGameSetup([NotNull] GameSetupParser.FinishGameSetupContext context);
}
