//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PlatformerMap.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PlatformerMapParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IPlatformerMapListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] PlatformerMapParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] PlatformerMapParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElem([NotNull] PlatformerMapParser.ElemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElem([NotNull] PlatformerMapParser.ElemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.addStartSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddStartSegment([NotNull] PlatformerMapParser.AddStartSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.addStartSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddStartSegment([NotNull] PlatformerMapParser.AddStartSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.addFlatPathSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddFlatPathSegment([NotNull] PlatformerMapParser.AddFlatPathSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.addFlatPathSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddFlatPathSegment([NotNull] PlatformerMapParser.AddFlatPathSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.addLowPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddLowPlatformSegment([NotNull] PlatformerMapParser.AddLowPlatformSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.addLowPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddLowPlatformSegment([NotNull] PlatformerMapParser.AddLowPlatformSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.addHighPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddHighPlatformSegment([NotNull] PlatformerMapParser.AddHighPlatformSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.addHighPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddHighPlatformSegment([NotNull] PlatformerMapParser.AddHighPlatformSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.addPathGapSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddPathGapSegment([NotNull] PlatformerMapParser.AddPathGapSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.addPathGapSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddPathGapSegment([NotNull] PlatformerMapParser.AddPathGapSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlatformerMapParser.addFinishLineSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddFinishLineSegment([NotNull] PlatformerMapParser.AddFinishLineSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlatformerMapParser.addFinishLineSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddFinishLineSegment([NotNull] PlatformerMapParser.AddFinishLineSegmentContext context);
}
