//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from proto101.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Iproto101Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class proto101BaseListener : Iproto101Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] proto101Parser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] proto101Parser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElem([NotNull] proto101Parser.ElemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElem([NotNull] proto101Parser.ElemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.initialiseGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialiseGame([NotNull] proto101Parser.InitialiseGameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.initialiseGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialiseGame([NotNull] proto101Parser.InitialiseGameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.defineGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineGame([NotNull] proto101Parser.DefineGameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.defineGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineGame([NotNull] proto101Parser.DefineGameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.createPlayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatePlayer([NotNull] proto101Parser.CreatePlayerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.createPlayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatePlayer([NotNull] proto101Parser.CreatePlayerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.createDungeon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateDungeon([NotNull] proto101Parser.CreateDungeonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.createDungeon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateDungeon([NotNull] proto101Parser.CreateDungeonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.createEnemies"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateEnemies([NotNull] proto101Parser.CreateEnemiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.createEnemies"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateEnemies([NotNull] proto101Parser.CreateEnemiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addStartSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddStartSegment([NotNull] proto101Parser.AddStartSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addStartSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddStartSegment([NotNull] proto101Parser.AddStartSegmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addFlatPathSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddFlatPathSegment([NotNull] proto101Parser.AddFlatPathSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addFlatPathSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddFlatPathSegment([NotNull] proto101Parser.AddFlatPathSegmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addLowPlatformSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddLowPlatformSegment([NotNull] proto101Parser.AddLowPlatformSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addLowPlatformSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddLowPlatformSegment([NotNull] proto101Parser.AddLowPlatformSegmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addHighPlatformSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddHighPlatformSegment([NotNull] proto101Parser.AddHighPlatformSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addHighPlatformSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddHighPlatformSegment([NotNull] proto101Parser.AddHighPlatformSegmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addPathGapSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddPathGapSegment([NotNull] proto101Parser.AddPathGapSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addPathGapSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddPathGapSegment([NotNull] proto101Parser.AddPathGapSegmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addFinishLineSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddFinishLineSegment([NotNull] proto101Parser.AddFinishLineSegmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addFinishLineSegment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddFinishLineSegment([NotNull] proto101Parser.AddFinishLineSegmentContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
