//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from proto101.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class proto101Lexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		INITIALISE=1, GAMETYPE=2, PC=3, NUM=4, DIFFICULTY=5, SKILLLEVEL=6, SKILLSET=7, 
		DUNGEON=8, PLATFORMER=9, MAP=10, SIZE=11, ENEMY=12, ATTACKSTYLE=13, START=14, 
		FLATPATH=15, LOWPLATFORM=16, HIGHPLATFORM=17, PATHGAP=18, FINISHLINE=19, 
		INT=20, NEWLINE=21, WS=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"INITIALISE", "GAMETYPE", "PC", "NUM", "DIFFICULTY", "SKILLLEVEL", "SKILLSET", 
		"DUNGEON", "PLATFORMER", "MAP", "SIZE", "ENEMY", "ATTACKSTYLE", "START", 
		"FLATPATH", "LOWPLATFORM", "HIGHPLATFORM", "PATHGAP", "FINISHLINE", "INT", 
		"NEWLINE", "WS"
	};


		public PrototypeCompiler Compiler = new PrototypeCompiler(); //this will be the compiler file in the Unity project


	public proto101Lexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public proto101Lexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'initialise'", null, "'players'", null, "'difficulty'", null, null, 
		"'dungeon'", "'platformer'", "'map'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "INITIALISE", "GAMETYPE", "PC", "NUM", "DIFFICULTY", "SKILLLEVEL", 
		"SKILLSET", "DUNGEON", "PLATFORMER", "MAP", "SIZE", "ENEMY", "ATTACKSTYLE", 
		"START", "FLATPATH", "LOWPLATFORM", "HIGHPLATFORM", "PATHGAP", "FINISHLINE", 
		"INT", "NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "proto101.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static proto101Lexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\xED', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', '=', '\n', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '\x63', '\n', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', 'y', 
		'\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x5', '\f', '\xA2', '\n', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', 
		'\r', '\xB0', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\xCC', '\n', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x5', '\x15', '\xDB', '\n', 
		'\x15', '\x3', '\x15', '\x6', '\x15', '\xDE', '\n', '\x15', '\r', '\x15', 
		'\xE', '\x15', '\xDF', '\x3', '\x16', '\x5', '\x16', '\xE3', '\n', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x6', '\x17', '\xE8', '\n', 
		'\x17', '\r', '\x17', '\xE', '\x17', '\xE9', '\x3', '\x17', '\x3', '\x17', 
		'\x2', '\x2', '\x18', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', 
		'\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', 
		'+', '\x17', '-', '\x18', '\x3', '\x2', '\t', '\x4', '\x2', 'U', 'U', 
		'u', 'u', '\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', 'R', 'R', 'r', 
		'r', '\x4', '\x2', 'J', 'J', 'j', 'j', '\x4', '\x2', 'I', 'I', 'i', 'i', 
		'\x4', '\x2', 'G', 'G', 'g', 'g', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x2', '\xFB', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x3', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '<', '\x3', '\x2', '\x2', '\x2', '\a', 
		'>', '\x3', '\x2', '\x2', '\x2', '\t', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'H', '\x3', '\x2', '\x2', '\x2', '\r', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'x', '\x3', '\x2', '\x2', '\x2', '\x11', 'z', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\x82', '\x3', '\x2', '\x2', '\x2', '\x15', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '\x17', '\xA1', '\x3', '\x2', '\x2', '\x2', 
		'\x19', '\xAF', '\x3', '\x2', '\x2', '\x2', '\x1B', '\xCB', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\xCD', '\x3', '\x2', '\x2', '\x2', '\x1F', '\xCF', 
		'\x3', '\x2', '\x2', '\x2', '!', '\xD1', '\x3', '\x2', '\x2', '\x2', '#', 
		'\xD3', '\x3', '\x2', '\x2', '\x2', '%', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\xD7', '\x3', '\x2', '\x2', '\x2', ')', '\xDA', '\x3', '\x2', 
		'\x2', '\x2', '+', '\xE2', '\x3', '\x2', '\x2', '\x2', '-', '\xE7', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x30', '\a', 'k', '\x2', '\x2', '\x30', '\x31', 
		'\a', 'p', '\x2', '\x2', '\x31', '\x32', '\a', 'k', '\x2', '\x2', '\x32', 
		'\x33', '\a', 'v', '\x2', '\x2', '\x33', '\x34', '\a', 'k', '\x2', '\x2', 
		'\x34', '\x35', '\a', '\x63', '\x2', '\x2', '\x35', '\x36', '\a', 'n', 
		'\x2', '\x2', '\x36', '\x37', '\a', 'k', '\x2', '\x2', '\x37', '\x38', 
		'\a', 'u', '\x2', '\x2', '\x38', '\x39', '\a', 'g', '\x2', '\x2', '\x39', 
		'\x4', '\x3', '\x2', '\x2', '\x2', ':', '=', '\x5', '\x11', '\t', '\x2', 
		';', '=', '\x5', '\x13', '\n', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', 
		'<', ';', '\x3', '\x2', '\x2', '\x2', '=', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '>', '?', '\a', 'r', '\x2', '\x2', '?', '@', '\a', 'n', '\x2', 
		'\x2', '@', '\x41', '\a', '\x63', '\x2', '\x2', '\x41', '\x42', '\a', 
		'{', '\x2', '\x2', '\x42', '\x43', '\a', 'g', '\x2', '\x2', '\x43', '\x44', 
		'\a', 't', '\x2', '\x2', '\x44', '\x45', '\a', 'u', '\x2', '\x2', '\x45', 
		'\b', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\x5', ')', '\x15', '\x2', 
		'G', '\n', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', '\x66', '\x2', 
		'\x2', 'I', 'J', '\a', 'k', '\x2', '\x2', 'J', 'K', '\a', 'h', '\x2', 
		'\x2', 'K', 'L', '\a', 'h', '\x2', '\x2', 'L', 'M', '\a', 'k', '\x2', 
		'\x2', 'M', 'N', '\a', '\x65', '\x2', '\x2', 'N', 'O', '\a', 'w', '\x2', 
		'\x2', 'O', 'P', '\a', 'n', '\x2', '\x2', 'P', 'Q', '\a', 'v', '\x2', 
		'\x2', 'Q', 'R', '\a', '{', '\x2', '\x2', 'R', '\f', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', 'g', '\x2', '\x2', 'T', 'U', '\a', '\x63', '\x2', 
		'\x2', 'U', 'V', '\a', 'u', '\x2', '\x2', 'V', '\x63', '\a', '{', '\x2', 
		'\x2', 'W', 'X', '\a', 't', '\x2', '\x2', 'X', 'Y', '\a', 'g', '\x2', 
		'\x2', 'Y', 'Z', '\a', 'i', '\x2', '\x2', 'Z', '[', '\a', 'w', '\x2', 
		'\x2', '[', '\\', '\a', 'n', '\x2', '\x2', '\\', ']', '\a', '\x63', '\x2', 
		'\x2', ']', '\x63', '\a', 't', '\x2', '\x2', '^', '_', '\a', 'j', '\x2', 
		'\x2', '_', '`', '\a', '\x63', '\x2', '\x2', '`', '\x61', '\a', 't', '\x2', 
		'\x2', '\x61', '\x63', '\a', '\x66', '\x2', '\x2', '\x62', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x62', 'W', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'^', '\x3', '\x2', '\x2', '\x2', '\x63', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x65', '\a', '\x64', '\x2', '\x2', '\x65', '\x66', '\a', '\x63', 
		'\x2', '\x2', '\x66', 'g', '\a', 'u', '\x2', '\x2', 'g', 'h', '\a', 'k', 
		'\x2', '\x2', 'h', 'y', '\a', '\x65', '\x2', '\x2', 'i', 'j', '\a', '\x64', 
		'\x2', '\x2', 'j', 'k', '\a', '\x63', '\x2', '\x2', 'k', 'l', '\a', 'n', 
		'\x2', '\x2', 'l', 'm', '\a', '\x63', '\x2', '\x2', 'm', 'n', '\a', 'p', 
		'\x2', '\x2', 'n', 'o', '\a', '\x65', '\x2', '\x2', 'o', 'p', '\a', 'g', 
		'\x2', '\x2', 'p', 'y', '\a', '\x66', '\x2', '\x2', 'q', 'r', '\a', 'u', 
		'\x2', '\x2', 'r', 's', '\a', 'm', '\x2', '\x2', 's', 't', '\a', 'k', 
		'\x2', '\x2', 't', 'u', '\a', 'n', '\x2', '\x2', 'u', 'v', '\a', 'n', 
		'\x2', '\x2', 'v', 'w', '\a', 'g', '\x2', '\x2', 'w', 'y', '\a', '\x66', 
		'\x2', '\x2', 'x', '\x64', '\x3', '\x2', '\x2', '\x2', 'x', 'i', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'q', '\x3', '\x2', '\x2', '\x2', 'y', '\x10', 
		'\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '\x66', '\x2', '\x2', '{', 
		'|', '\a', 'w', '\x2', '\x2', '|', '}', '\a', 'p', '\x2', '\x2', '}', 
		'~', '\a', 'i', '\x2', '\x2', '~', '\x7F', '\a', 'g', '\x2', '\x2', '\x7F', 
		'\x80', '\a', 'q', '\x2', '\x2', '\x80', '\x81', '\a', 'p', '\x2', '\x2', 
		'\x81', '\x12', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', 'r', 
		'\x2', '\x2', '\x83', '\x84', '\a', 'n', '\x2', '\x2', '\x84', '\x85', 
		'\a', '\x63', '\x2', '\x2', '\x85', '\x86', '\a', 'v', '\x2', '\x2', '\x86', 
		'\x87', '\a', 'h', '\x2', '\x2', '\x87', '\x88', '\a', 'q', '\x2', '\x2', 
		'\x88', '\x89', '\a', 't', '\x2', '\x2', '\x89', '\x8A', '\a', 'o', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', 'g', '\x2', '\x2', '\x8B', '\x8C', '\a', 
		't', '\x2', '\x2', '\x8C', '\x14', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\a', 'o', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x63', '\x2', 
		'\x2', '\x8F', '\x90', '\a', 'r', '\x2', '\x2', '\x90', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x92', '\a', 'u', '\x2', '\x2', '\x92', 
		'\x93', '\a', 'o', '\x2', '\x2', '\x93', '\x94', '\a', '\x63', '\x2', 
		'\x2', '\x94', '\x95', '\a', 'n', '\x2', '\x2', '\x95', '\xA2', '\a', 
		'n', '\x2', '\x2', '\x96', '\x97', '\a', 'o', '\x2', '\x2', '\x97', '\x98', 
		'\a', 'g', '\x2', '\x2', '\x98', '\x99', '\a', '\x66', '\x2', '\x2', '\x99', 
		'\x9A', '\a', 'k', '\x2', '\x2', '\x9A', '\x9B', '\a', 'w', '\x2', '\x2', 
		'\x9B', '\xA2', '\a', 'o', '\x2', '\x2', '\x9C', '\x9D', '\a', 'n', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', '\x63', '\x2', '\x2', '\x9E', '\x9F', '\a', 
		't', '\x2', '\x2', '\x9F', '\xA0', '\a', 'i', '\x2', '\x2', '\xA0', '\xA2', 
		'\a', 'g', '\x2', '\x2', '\xA1', '\x91', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\xA2', '\x18', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\a', 
		'g', '\x2', '\x2', '\xA4', '\xA5', '\a', 'p', '\x2', '\x2', '\xA5', '\xA6', 
		'\a', 'g', '\x2', '\x2', '\xA6', '\xA7', '\a', 'o', '\x2', '\x2', '\xA7', 
		'\xB0', '\a', '{', '\x2', '\x2', '\xA8', '\xA9', '\a', 'g', '\x2', '\x2', 
		'\xA9', '\xAA', '\a', 'p', '\x2', '\x2', '\xAA', '\xAB', '\a', 'g', '\x2', 
		'\x2', '\xAB', '\xAC', '\a', 'o', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'k', '\x2', '\x2', '\xAD', '\xAE', '\a', 'g', '\x2', '\x2', '\xAE', '\xB0', 
		'\a', 'u', '\x2', '\x2', '\xAF', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\xB0', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xB2', '\a', 'r', '\x2', '\x2', '\xB2', '\xB3', '\a', 
		't', '\x2', '\x2', '\xB3', '\xB4', '\a', 'q', '\x2', '\x2', '\xB4', '\xB5', 
		'\a', 'l', '\x2', '\x2', '\xB5', '\xB6', '\a', 'g', '\x2', '\x2', '\xB6', 
		'\xB7', '\a', '\x65', '\x2', '\x2', '\xB7', '\xB8', '\a', 'v', '\x2', 
		'\x2', '\xB8', '\xB9', '\a', 'k', '\x2', '\x2', '\xB9', '\xBA', '\a', 
		'n', '\x2', '\x2', '\xBA', '\xCC', '\a', 'g', '\x2', '\x2', '\xBB', '\xBC', 
		'\a', 'o', '\x2', '\x2', '\xBC', '\xBD', '\a', 'g', '\x2', '\x2', '\xBD', 
		'\xBE', '\a', 'n', '\x2', '\x2', '\xBE', '\xBF', '\a', 'g', '\x2', '\x2', 
		'\xBF', '\xCC', '\a', 'g', '\x2', '\x2', '\xC0', '\xC1', '\a', 'x', '\x2', 
		'\x2', '\xC1', '\xC2', '\a', '\x63', '\x2', '\x2', '\xC2', '\xC3', '\a', 
		't', '\x2', '\x2', '\xC3', '\xC4', '\a', 'k', '\x2', '\x2', '\xC4', '\xC5', 
		'\a', 'g', '\x2', '\x2', '\xC5', '\xCC', '\a', '\x66', '\x2', '\x2', '\xC6', 
		'\xC7', '\a', '\x65', '\x2', '\x2', '\xC7', '\xC8', '\a', 'q', '\x2', 
		'\x2', '\xC8', '\xC9', '\a', 'o', '\x2', '\x2', '\xC9', '\xCA', '\a', 
		'\x64', '\x2', '\x2', '\xCA', '\xCC', '\a', 'q', '\x2', '\x2', '\xCB', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\xCB', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC6', '\x3', 
		'\x2', '\x2', '\x2', '\xCC', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xCE', '\t', '\x2', '\x2', '\x2', '\xCE', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xD0', '\t', '\x3', '\x2', '\x2', '\xD0', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xD2', '\t', '\x4', '\x2', '\x2', '\xD2', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\t', '\x5', '\x2', 
		'\x2', '\xD4', '$', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\t', 
		'\x6', '\x2', '\x2', '\xD6', '&', '\x3', '\x2', '\x2', '\x2', '\xD7', 
		'\xD8', '\t', '\a', '\x2', '\x2', '\xD8', '(', '\x3', '\x2', '\x2', '\x2', 
		'\xD9', '\xDB', '\a', '/', '\x2', '\x2', '\xDA', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '\xDA', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDD', 
		'\x3', '\x2', '\x2', '\x2', '\xDC', '\xDE', '\x4', '\x32', ';', '\x2', 
		'\xDD', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\x3', '\x2', 
		'\x2', '\x2', '\xDF', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE0', 
		'\x3', '\x2', '\x2', '\x2', '\xE0', '*', '\x3', '\x2', '\x2', '\x2', '\xE1', 
		'\xE3', '\a', '\xF', '\x2', '\x2', '\xE2', '\xE1', '\x3', '\x2', '\x2', 
		'\x2', '\xE2', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', '\xE4', '\xE5', '\a', '\f', '\x2', '\x2', '\xE5', 
		',', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE8', '\t', '\b', '\x2', '\x2', 
		'\xE7', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\x3', '\x2', 
		'\x2', '\x2', '\xE9', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', 
		'\x3', '\x2', '\x2', '\x2', '\xEA', '\xEB', '\x3', '\x2', '\x2', '\x2', 
		'\xEB', '\xEC', '\b', '\x17', '\x2', '\x2', '\xEC', '.', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x2', '<', '\x62', 'x', '\xA1', '\xAF', '\xCB', '\xDA', 
		'\xDF', '\xE2', '\xE9', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
