//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from proto101.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="proto101Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface Iproto101Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] proto101Parser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] proto101Parser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElem([NotNull] proto101Parser.ElemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElem([NotNull] proto101Parser.ElemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.createGame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateGame([NotNull] proto101Parser.CreateGameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.createGame"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateGame([NotNull] proto101Parser.CreateGameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.createPlayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreatePlayer([NotNull] proto101Parser.CreatePlayerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.createPlayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreatePlayer([NotNull] proto101Parser.CreatePlayerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.createDungeon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateDungeon([NotNull] proto101Parser.CreateDungeonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.createDungeon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateDungeon([NotNull] proto101Parser.CreateDungeonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.createEnemies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateEnemies([NotNull] proto101Parser.CreateEnemiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.createEnemies"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateEnemies([NotNull] proto101Parser.CreateEnemiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addStartSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddStartSegment([NotNull] proto101Parser.AddStartSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addStartSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddStartSegment([NotNull] proto101Parser.AddStartSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addFlatPathSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddFlatPathSegment([NotNull] proto101Parser.AddFlatPathSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addFlatPathSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddFlatPathSegment([NotNull] proto101Parser.AddFlatPathSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addLowPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddLowPlatformSegment([NotNull] proto101Parser.AddLowPlatformSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addLowPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddLowPlatformSegment([NotNull] proto101Parser.AddLowPlatformSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addHighPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddHighPlatformSegment([NotNull] proto101Parser.AddHighPlatformSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addHighPlatformSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddHighPlatformSegment([NotNull] proto101Parser.AddHighPlatformSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addPathGapSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddPathGapSegment([NotNull] proto101Parser.AddPathGapSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addPathGapSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddPathGapSegment([NotNull] proto101Parser.AddPathGapSegmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="proto101Parser.addFinishLineSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddFinishLineSegment([NotNull] proto101Parser.AddFinishLineSegmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="proto101Parser.addFinishLineSegment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddFinishLineSegment([NotNull] proto101Parser.AddFinishLineSegmentContext context);
}
