//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DungeonMap.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DungeonMapParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IDungeonMapListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] DungeonMapParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] DungeonMapParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElem([NotNull] DungeonMapParser.ElemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElem([NotNull] DungeonMapParser.ElemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createInitialRoom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateInitialRoom([NotNull] DungeonMapParser.CreateInitialRoomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createInitialRoom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateInitialRoom([NotNull] DungeonMapParser.CreateInitialRoomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createFirstCorrSect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateFirstCorrSect([NotNull] DungeonMapParser.CreateFirstCorrSectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createFirstCorrSect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateFirstCorrSect([NotNull] DungeonMapParser.CreateFirstCorrSectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createSecondCorrSect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateSecondCorrSect([NotNull] DungeonMapParser.CreateSecondCorrSectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createSecondCorrSect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateSecondCorrSect([NotNull] DungeonMapParser.CreateSecondCorrSectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createRoom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateRoom([NotNull] DungeonMapParser.CreateRoomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createRoom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateRoom([NotNull] DungeonMapParser.CreateRoomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DungeonMapParser.createFinalRoom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreateFinalRoom([NotNull] DungeonMapParser.CreateFinalRoomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DungeonMapParser.createFinalRoom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreateFinalRoom([NotNull] DungeonMapParser.CreateFinalRoomContext context);
}
