//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DungeonMap.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class DungeonMapParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		INITROOM=1, ENTRY=2, EXIT=3, DIRECTION=4, ROOM=5, FINALROOM=6, INT=7, 
		NEWLINE=8, WS=9;
	public const int
		RULE_prog = 0, RULE_elem = 1, RULE_createInitialRoom = 2, RULE_createFirstCorrSect = 3, 
		RULE_createSecondCorrSect = 4, RULE_createRoom = 5, RULE_createFinalRoom = 6;
	public static readonly string[] ruleNames = {
		"prog", "elem", "createInitialRoom", "createFirstCorrSect", "createSecondCorrSect", 
		"createRoom", "createFinalRoom"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "'r'", "'z'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "INITROOM", "ENTRY", "EXIT", "DIRECTION", "ROOM", "FINALROOM", "INT", 
		"NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DungeonMap.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DungeonMapParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}


		public DungeonCompiler Compiler = new DungeonCompiler(); //specific compiler file in the Unity project

		public DungeonMapParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DungeonMapParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgContext : ParserRuleContext {
		public ElemContext[] elem() {
			return GetRuleContexts<ElemContext>();
		}
		public ElemContext elem(int i) {
			return GetRuleContext<ElemContext>(i);
		}
		public ProgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prog; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.EnterProg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.ExitProg(this);
		}
	}

	[RuleVersion(0)]
	public ProgContext prog() {
		ProgContext _localctx = new ProgContext(Context, State);
		EnterRule(_localctx, 0, RULE_prog);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 15;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 14; elem();
				}
				}
				State = 17;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INITROOM) | (1L << ENTRY) | (1L << DIRECTION))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElemContext : ParserRuleContext {
		public ITerminalNode NEWLINE() { return GetToken(DungeonMapParser.NEWLINE, 0); }
		public CreateInitialRoomContext createInitialRoom() {
			return GetRuleContext<CreateInitialRoomContext>(0);
		}
		public CreateFirstCorrSectContext createFirstCorrSect() {
			return GetRuleContext<CreateFirstCorrSectContext>(0);
		}
		public CreateSecondCorrSectContext createSecondCorrSect() {
			return GetRuleContext<CreateSecondCorrSectContext>(0);
		}
		public CreateRoomContext createRoom() {
			return GetRuleContext<CreateRoomContext>(0);
		}
		public CreateFinalRoomContext createFinalRoom() {
			return GetRuleContext<CreateFinalRoomContext>(0);
		}
		public ElemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elem; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.EnterElem(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.ExitElem(this);
		}
	}

	[RuleVersion(0)]
	public ElemContext elem() {
		ElemContext _localctx = new ElemContext(Context, State);
		EnterRule(_localctx, 2, RULE_elem);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				State = 19; createInitialRoom();
				}
				break;
			case 2:
				{
				State = 20; createFirstCorrSect();
				}
				break;
			case 3:
				{
				State = 21; createSecondCorrSect();
				}
				break;
			case 4:
				{
				State = 22; createRoom();
				}
				break;
			case 5:
				{
				State = 23; createFinalRoom();
				}
				break;
			}
			State = 26; Match(NEWLINE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CreateInitialRoomContext : ParserRuleContext {
		public IToken _EXIT;
		public ITerminalNode INITROOM() { return GetToken(DungeonMapParser.INITROOM, 0); }
		public ITerminalNode EXIT() { return GetToken(DungeonMapParser.EXIT, 0); }
		public CreateInitialRoomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_createInitialRoom; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.EnterCreateInitialRoom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.ExitCreateInitialRoom(this);
		}
	}

	[RuleVersion(0)]
	public CreateInitialRoomContext createInitialRoom() {
		CreateInitialRoomContext _localctx = new CreateInitialRoomContext(Context, State);
		EnterRule(_localctx, 4, RULE_createInitialRoom);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28; Match(INITROOM);
			State = 29; _localctx._EXIT = Match(EXIT);
			 Compiler.CreateInitialRoom((_localctx._EXIT!=null?_localctx._EXIT.Text:null)); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CreateFirstCorrSectContext : ParserRuleContext {
		public IToken _ENTRY;
		public IToken _DIRECTION;
		public ITerminalNode ENTRY() { return GetToken(DungeonMapParser.ENTRY, 0); }
		public ITerminalNode DIRECTION() { return GetToken(DungeonMapParser.DIRECTION, 0); }
		public CreateFirstCorrSectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_createFirstCorrSect; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.EnterCreateFirstCorrSect(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.ExitCreateFirstCorrSect(this);
		}
	}

	[RuleVersion(0)]
	public CreateFirstCorrSectContext createFirstCorrSect() {
		CreateFirstCorrSectContext _localctx = new CreateFirstCorrSectContext(Context, State);
		EnterRule(_localctx, 6, RULE_createFirstCorrSect);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32; _localctx._ENTRY = Match(ENTRY);
			State = 33; _localctx._DIRECTION = Match(DIRECTION);
			 Compiler.CreateFirstPiece((_localctx._ENTRY!=null?_localctx._ENTRY.Text:null), (_localctx._DIRECTION!=null?_localctx._DIRECTION.Text:null)); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CreateSecondCorrSectContext : ParserRuleContext {
		public IToken _DIRECTION;
		public IToken _EXIT;
		public ITerminalNode DIRECTION() { return GetToken(DungeonMapParser.DIRECTION, 0); }
		public ITerminalNode EXIT() { return GetToken(DungeonMapParser.EXIT, 0); }
		public CreateSecondCorrSectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_createSecondCorrSect; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.EnterCreateSecondCorrSect(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.ExitCreateSecondCorrSect(this);
		}
	}

	[RuleVersion(0)]
	public CreateSecondCorrSectContext createSecondCorrSect() {
		CreateSecondCorrSectContext _localctx = new CreateSecondCorrSectContext(Context, State);
		EnterRule(_localctx, 8, RULE_createSecondCorrSect);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36; _localctx._DIRECTION = Match(DIRECTION);
			State = 37; _localctx._EXIT = Match(EXIT);
			 Compiler.CreateSecondPiece((_localctx._DIRECTION!=null?_localctx._DIRECTION.Text:null), (_localctx._EXIT!=null?_localctx._EXIT.Text:null)); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CreateRoomContext : ParserRuleContext {
		public IToken _ENTRY;
		public IToken _EXIT;
		public ITerminalNode ENTRY() { return GetToken(DungeonMapParser.ENTRY, 0); }
		public ITerminalNode ROOM() { return GetToken(DungeonMapParser.ROOM, 0); }
		public ITerminalNode EXIT() { return GetToken(DungeonMapParser.EXIT, 0); }
		public CreateRoomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_createRoom; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.EnterCreateRoom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.ExitCreateRoom(this);
		}
	}

	[RuleVersion(0)]
	public CreateRoomContext createRoom() {
		CreateRoomContext _localctx = new CreateRoomContext(Context, State);
		EnterRule(_localctx, 10, RULE_createRoom);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 40; _localctx._ENTRY = Match(ENTRY);
			State = 41; Match(ROOM);
			State = 42; _localctx._EXIT = Match(EXIT);
			 Compiler.CreateRoom((_localctx._ENTRY!=null?_localctx._ENTRY.Text:null), (_localctx._EXIT!=null?_localctx._EXIT.Text:null)); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CreateFinalRoomContext : ParserRuleContext {
		public IToken _ENTRY;
		public ITerminalNode ENTRY() { return GetToken(DungeonMapParser.ENTRY, 0); }
		public ITerminalNode FINALROOM() { return GetToken(DungeonMapParser.FINALROOM, 0); }
		public CreateFinalRoomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_createFinalRoom; } }
		public override void EnterRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.EnterCreateFinalRoom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IDungeonMapListener typedListener = listener as IDungeonMapListener;
			if (typedListener != null) typedListener.ExitCreateFinalRoom(this);
		}
	}

	[RuleVersion(0)]
	public CreateFinalRoomContext createFinalRoom() {
		CreateFinalRoomContext _localctx = new CreateFinalRoomContext(Context, State);
		EnterRule(_localctx, 12, RULE_createFinalRoom);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45; _localctx._ENTRY = Match(ENTRY);
			State = 46; Match(FINALROOM);
			 Compiler.CreateFinalRoom((_localctx._ENTRY!=null?_localctx._ENTRY.Text:null)); 
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\v', '\x34', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x3', '\x2', '\x6', '\x2', '\x12', '\n', '\x2', '\r', '\x2', '\xE', '\x2', 
		'\x13', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x5', '\x3', '\x1B', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x2', '\x2', '\t', '\x2', '\x4', '\x6', '\b', '\n', '\f', 
		'\xE', '\x2', '\x2', '\x2', '\x31', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x4', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x6', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\b', '\"', '\x3', '\x2', '\x2', '\x2', '\n', '&', 
		'\x3', '\x2', '\x2', '\x2', '\f', '*', '\x3', '\x2', '\x2', '\x2', '\xE', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x10', '\x12', '\x5', '\x4', '\x3', 
		'\x2', '\x11', '\x10', '\x3', '\x2', '\x2', '\x2', '\x12', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x11', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x14', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x1B', '\x5', '\x6', '\x4', '\x2', '\x16', '\x1B', '\x5', 
		'\b', '\x5', '\x2', '\x17', '\x1B', '\x5', '\n', '\x6', '\x2', '\x18', 
		'\x1B', '\x5', '\f', '\a', '\x2', '\x19', '\x1B', '\x5', '\xE', '\b', 
		'\x2', '\x1A', '\x15', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x16', '\x3', 
		'\x2', '\x2', '\x2', '\x1A', '\x17', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\a', 
		'\n', '\x2', '\x2', '\x1D', '\x5', '\x3', '\x2', '\x2', '\x2', '\x1E', 
		'\x1F', '\a', '\x3', '\x2', '\x2', '\x1F', ' ', '\a', '\x5', '\x2', '\x2', 
		' ', '!', '\b', '\x4', '\x1', '\x2', '!', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\"', '#', '\a', '\x4', '\x2', '\x2', '#', '$', '\a', '\x6', '\x2', '\x2', 
		'$', '%', '\b', '\x5', '\x1', '\x2', '%', '\t', '\x3', '\x2', '\x2', '\x2', 
		'&', '\'', '\a', '\x6', '\x2', '\x2', '\'', '(', '\a', '\x5', '\x2', '\x2', 
		'(', ')', '\b', '\x6', '\x1', '\x2', ')', '\v', '\x3', '\x2', '\x2', '\x2', 
		'*', '+', '\a', '\x4', '\x2', '\x2', '+', ',', '\a', '\a', '\x2', '\x2', 
		',', '-', '\a', '\x5', '\x2', '\x2', '-', '.', '\b', '\a', '\x1', '\x2', 
		'.', '\r', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\a', '\x4', '\x2', 
		'\x2', '\x30', '\x31', '\a', '\b', '\x2', '\x2', '\x31', '\x32', '\b', 
		'\b', '\x1', '\x2', '\x32', '\xF', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'\x13', '\x1A',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
