//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GameSetup.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGameSetupListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class GameSetupBaseListener : IGameSetupListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] GameSetupParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] GameSetupParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElem([NotNull] GameSetupParser.ElemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.elem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElem([NotNull] GameSetupParser.ElemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.initialiseGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialiseGame([NotNull] GameSetupParser.InitialiseGameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.initialiseGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialiseGame([NotNull] GameSetupParser.InitialiseGameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.defineGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefineGame([NotNull] GameSetupParser.DefineGameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.defineGame"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefineGame([NotNull] GameSetupParser.DefineGameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.createPlayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatePlayer([NotNull] GameSetupParser.CreatePlayerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.createPlayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatePlayer([NotNull] GameSetupParser.CreatePlayerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.createDungeon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateDungeon([NotNull] GameSetupParser.CreateDungeonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.createDungeon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateDungeon([NotNull] GameSetupParser.CreateDungeonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.createEnemies"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreateEnemies([NotNull] GameSetupParser.CreateEnemiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.createEnemies"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreateEnemies([NotNull] GameSetupParser.CreateEnemiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GameSetupParser.finishGameSetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinishGameSetup([NotNull] GameSetupParser.FinishGameSetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GameSetupParser.finishGameSetup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinishGameSetup([NotNull] GameSetupParser.FinishGameSetupContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
